### ISSUE TITLE
Ansible - install .NET Core 3.0

### ISSUE THREAD

**Issue by dermeister0** [Saritasa/dotnet-deploy#12]
```
- name: Install .NET Core Runtime
  win_chocolatey:
    name: dotnetcore-runtime
    version: 3.0.0
  become: yes
  register: runtime_result
- name: Install .NET Core Windows Server Hosting
  win_package:
    path: https://download.visualstudio.microsoft.com/download/pr/bf608208-38aa-4a40-9b71-ae3b251e110a/bc1cecb14f75cc83dcd4bbc3309f7086/dotnet-hosting-3.0.0-win.exe
    product_id: '{73F8C23D-8F4A-42E4-AC06-135159FFF9DB}'
    arguments: /install /quiet OPT_NO_RUNTIME=true
  register: hosting_result
- name: Restart server
  win_reboot:
  when: (runtime_result.rc is defined and runtime_result.rc == 3010) or (hosting_result.rc is defined and hosting_result.rc == 3010)
```
